name: Build and Publish Electron App

on:
  push:
    tags:
      - 'v*' # 当推送形如 v1.0.1 的 tag 时触发自动打包发布

permissions:
  contents: write # 赋予 Action 往 Releases 写入二进制文件的权限

jobs:
  release:
    name: Build & Publish (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest] # 分别在 Windows 和 macOS 镜像中编译

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and Publish
        run: npm run publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub 自动提供的内置 Token 授权，无需手动配置

      - name: Update Release Notes
        run: gh release edit ${{ github.ref_name }} --notes-file release-notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
